### ISSUE TITLE
Mejorar y añadir a la guia oficial

### ISSUE THREAD

**Issue by m1guelpf** [jkcgs/Guide#11]
Hola!
Estaba pensando en hacer una versión en español y me he encontrado con que te has adelantado!
Me gustaría ayudarte y pasar esto al formato oficial para permitir incluirlo en la guia oficial.
Un saludo!

**Comment by jkcgs** [comment]
Lamento responder tan tarde 😞 
¿A qué te referías con el formato oficial? Es un fork, así que prácticamente es lo mismo pero en Español.

**Comment by m1guelpf** [comment]
Pladilect va a añadir soporte para traducciones

**Comment by jkcgs** [comment]
Lo sé, y estoy en el grupo de coordinación, tal como te respondí en GBAtemp

**Comment by m1guelpf** [comment]
Opps no lo vi
